import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner/banner';
import Card from '../components/card/card';
import styles from '../styles/Home.module.css';
import CoffieStores from "./../data/coffee-stores.json";
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';
import { CardCoffieShopData } from "./../dataModel/cardCoffieShopData";
interface HomeProps {
src:string ;
alt: string;
height:number;
width:number;
CoffieStores:Array<CardCoffieShopData>;
} 


export async function getStaticProps(context:any) {
  return {
    props: {CoffieStores}, // will be passed to the page component as props
  }
}


 const Home:React.FC<HomeProps> = ({src,alt,height ,width,CoffieStores}) => {

console.log("coffieconsi",CoffieStores)

const handleOnBannerBtnClick = () => {
console.log("AAAAAAHHH");  
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffie Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main className={styles.main}>
       <Banner buttonText="View Stores Near By" handleOnClick={handleOnBannerBtnClick}  />
       <div className={styles.heroImage}>
       <Image src="/static/hero-image.png" alt="another" width={700} height={400} />
       </div>
       { CoffieStores.length > 0 && 
       <>
       <div> 
       <h2 className={styles.heading2}>Toronto Stores</h2>
       <div className={styles.cardLayout} >
   
      { CoffieStores.map((CoffieStore :any) => {
      return (
        <Card 
         key={CoffieStore.id}
         name={CoffieStore.name}
         imgUrl={CoffieStore.imgUrl}
         href={`/coffee-store/${CoffieStore.id}`}
         className={styles.card}
         />
      )   
      }  
      )}
      </div>
      </div>
      </>
      }


      </main>
  </div>
  )
}

export default Home;