import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner/banner';
import Card from '../components/card/card';
import styles from '../styles/Home.module.css';


interface HomeProps {
src:string ;
alt: string;
height:number;
width:number;
} 

 const Home:React.FC<HomeProps> = ({src,alt,height ,width}) => {

  

const handleOnBannerBtnClick = () => {
console.log("AAAAAAHHH");  
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffie Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main className={styles.main}>
       <Banner buttonText="View Stores Near By" handleOnClick={handleOnBannerBtnClick}  />
       <div className={styles.heroImage}>
       <Image src="/static/hero-image.png" alt="another" width={700} height={400} />
       </div>
       <Card 
        name='Dark Horse Coffee'
        imgUrl='/hero-image.png'
        href="/coffee-store/darkhorse-coffee"

        
       
       />
      </main>
  </div>
  )
}

export default Home;